---
title: "Third_Party_PreProcessing_Code.Rmd"
output: html_document
date: "2023-06-16"
---

# load data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(dplyr)
library(ggplot2)

gene_counts<-readr::read_tsv("/path/to/third_party/GSE146889_GeneCount.tsv")

```

The structure of the GSE146889 file goes: counts, RPKM, counts, RPKM
We also want to group by file type (in name)
```{r}
# we want to make row names the gene_counts$GeneName column BUT they aren't unique
rownames(gene_counts) <- gene_counts$GeneId # but GeneID is unique, we can always convert later

# drop the first 7 columns
gene_counts <- select(gene_counts, -(1:7))

# and then we get rid of RPKMs
gene_counts <- select(gene_counts, -contains("RPKM"))

saveRDS(gene_counts, "/path/to/third_party/GSE146889_GeneCount.rds")


# and separate the tumours from the normals
normal_gene_counts <- select(gene_counts, contains("normal"))
tumor_gene_counts <- select(gene_counts, contains("tumor"))





```

Great, now lets look at the data!
Useful functions:
```{r}
compute_mean_dispersion <- function(x) {
  mean_val <- mean(x)
  variance <- var(x)
  Std.Dev=sd(x)
  return(c(mean_val, Std.Dev))
}

# thing is, Splatter paper was log2(CPM + 1), so I need to compute that
# for all genes, compute counts /total counts for each individual, times a million

compute_log2_cpm_plus1 <- function(df) {
  # compute the total counts for each sample
  sample_counts <- colSums(df)
  # compute the CPM for each gene
  cpm <- sweep(df, 2, sample_counts, "/") * 1e6
  log2cpm_plus1 <- log((cpm+1), base = 2)
  
  return(cpm)
}
```

And analysis
```{r}
# pretty sure this is accurate
tumor_logcpm <- compute_log2_cpm_plus1(tumor_gene_counts)
normal_logcpm <- compute_log2_cpm_plus1(normal_gene_counts)

tumor_dispersion <- apply(tumor_logcpm, 1, compute_mean_dispersion)
normal_dispersion <- apply(normal_logcpm, 1, compute_mean_dispersion)

tumor_dispersion_df <- data.frame(t(tumor_dispersion))
tumor_dispersion_df <- tumor_dispersion_df[which(rownames(tumor_dispersion_df) != "ENSG00000251562"),]
names(tumor_dispersion_df) <- c("mean", "dispersion")

normal_dispersion_df <- data.frame(t(normal_dispersion))
normal_dispersion_df <- normal_dispersion_df[which(rownames(normal_dispersion_df) != "ENSG00000251562"),]
names(normal_dispersion_df) <- c("mean", "dispersion")


mean_dispersion_plot <- ggplot() + 
    geom_point(data=tumor_dispersion_df, aes(x=mean, y=dispersion), colour="blue", alpha = 0.2) +
    geom_point(data=normal_dispersion_df, aes(x=mean, y=dispersion), colour="green", alpha = 0.2) +
    geom_smooth(data=tumor_dispersion_df, aes(x=mean, y=dispersion), colour="blue", method = "loess") +
    geom_smooth(data=normal_dispersion_df, aes(x=mean, y=dispersion), colour="green", method = "loess") 
    
plot(mean_dispersion_plot)

jpeg("rplot.jpg", width = 350, height = "350")
# 2. Create the plot
plot(x = my_data$wt, y = my_data$mpg,
     pch = 16, frame = FALSE,
     xlab = "wt", ylab = "mpg", col = "#2E9FDF")
# 3. Close the file
dev.off()



```



